/**
 * Interface to handle the events generated by the BoatForm Class
 */
package programming2.bradshawMarina.gui;

/**
 * @author Valentina
 */

import java.util.EventListener;

public interface BoatFormListener extends EventListener {

    public void boatformEventOccured(FormEvent e);

    public void showLeaseForm(FormEvent ev);
}
